// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./components/Header.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    'Mdi:arrowLeft': typeof import('~icons/mdi/arrow-left')['default']
    'Mdi:check': typeof import('~icons/mdi/check')['default']
    NurseForm: typeof import('./components/NurseForm.vue')['default']
    PatientsForm: typeof import('./components/PatientsForm.vue')['default']
    RegisterButtons: typeof import('./components/RegisterButtons.vue')['default']
    RegistersHeader: typeof import('./components/RegistersHeader.vue')['default']
  }
}

export { }
